const { PrismaClient } = require('../lib/generated/prisma');
const prisma = new PrismaClient();

async function main() {

  console.log('Mevcut veriler temizleniyor...');
  
  // Delete in correct order to avoid foreign key constraints
  await prisma.activity.deleteMany({});
  await prisma.billingLog.deleteMany({});
  await prisma.task.deleteMany({});
  await prisma.message.deleteMany({});
  await prisma.user.deleteMany({});
  await prisma.permission.deleteMany({});
  await prisma.role.deleteMany({});
  await prisma.product.deleteMany({});
  await prisma.notification.deleteMany({});
  await prisma.blockedIP.deleteMany({});
  await prisma.blockedUser.deleteMany({});

  console.log('Mevcut veriler temizlendi. Yeni veriler ekleniyor...');

  // First create users
  await prisma.user.createMany({
    data: [
      {
        id: 'user_123',
        name: 'Ahmet Kaya',
        email: 'ahmet@example.com',
        avatar: 'https://avatar.example.com/ahmet.jpg',
        globalEnabled: true,
        notifications: {
          daily: true,
          marketing: false,
          system: true,
          motivation: true
        },
        lastActivity: new Date('2025-01-24T18:30:00Z'),
        streak: 15,
        isPremium: true,
        status: 'active',
      },  
      {
        id: 'user_129',
        name: 'Mehmet Sari',
        email: 'mehmet@example.com',
        avatar: 'https://avatar.example.com/mehmet.jpg',
        globalEnabled: true,
        notifications: {
          daily: true,
          marketing: true,
          system: true,
          motivation: false
        },
        lastActivity: new Date('2025-01-24T14:20:00Z'),
        streak: 8,
        isPremium: false,
        status: 'active',
      },
      {
        id: 'user_130',
        name: 'Zeynep Koca',
        email: 'zeynep@example.com',
        avatar: 'https://avatar.example.com/zeynep.jpg',
        globalEnabled: false,
        notifications: {
          daily: false,
          marketing: false,
          system: true,
          motivation: true
        },
        lastActivity: new Date('2025-01-20T10:15:00Z'),
        streak: 3,
        isPremium: false,
        status: 'inactive',
      },
      {
        id: 'user_131',
        name: 'Ali Yurt',
        email: 'ali@example.com',
        avatar: 'https://avatar.example.com/ali.jpg',
        globalEnabled: true,
        notifications: {
          daily: true,
          marketing: true,
          system: true,
          motivation: true
        },
        lastActivity: new Date('2025-01-24T20:45:00Z'),
        streak: 22,
        isPremium: true,
        status: 'active',
      },
      {
        id: 'user_132',
        name: 'Burak Tekin',
        email: 'burak@example.com',
        avatar: null,
        globalEnabled: true,
        notifications: {
          daily: true,
          marketing: false,
          system: true,
          motivation: false
        },
        lastActivity: new Date('2025-01-23T16:30:00Z'),
        streak: 5,
        isPremium: false,
        status: 'active',
      },
      {
        id: 'user_133',
        name: 'Ayşe Mutlu',
        email: 'ayse@example.com',
        avatar: 'https://avatar.example.com/ayse.jpg',
        globalEnabled: true,
        notifications: {
          daily: true,
          marketing: true,
          system: true,
          motivation: true
        },
        lastActivity: new Date('2025-01-24T12:00:00Z'),
        streak: 12,
        isPremium: true,
        status: 'active',
      },
      {
        id: 'user_134',
        name: 'Cem Kara',
        email: 'cem@example.com',
        avatar: null,
        globalEnabled: false,
        notifications: {
          daily: false,
          marketing: false,
          system: false,
          motivation: false
        },
        lastActivity: new Date('2025-01-10T08:20:00Z'),
        streak: 0,
        isPremium: false,
        status: 'banned',
      },
      {
        id: 'user_135',
        name: 'Gizem Ak',
        email: 'gizem@example.com',
        avatar: 'https://avatar.example.com/gizem.jpg',
        globalEnabled: true,
        notifications: {
          daily: true,
          marketing: false,
          system: true,
          motivation: true
        },
        lastActivity: new Date('2025-01-24T21:10:00Z'),
        streak: 7,
        isPremium: false,
        status: 'active',
      },
      {
        id: 'user_136',
        name: 'Fatih Demir',
        email: 'fatih@example.com',
        avatar: 'https://avatar.example.com/fatih.jpg',
        globalEnabled: true,
        notifications: {
          daily: true,
          marketing: true,
          system: true,
          motivation: false
        },
        lastActivity: new Date('2025-01-24T09:45:00Z'),
        streak: 18,
        isPremium: true,
        status: 'active',
      },
    ],
  });

  // BlockedUser
  await prisma.blockedUser.createMany({
    data: [
      {
        username: 'john_doe',
        email: 'john@example.com',
        blockedDate: new Date('2024-01-15'),
        reason: 'Spam gönderimi',
        blockedBy: 'admin',
        status: 'active',
        blockedUntil: null,
      },
      {
        username: 'jane_smith',
        email: 'jane@example.com',
        blockedDate: new Date('2024-01-20'),
        reason: 'Uygunsuz içerik paylaşımı',
        blockedBy: 'moderator',
        status: 'temporary',
        blockedUntil: new Date('2024-08-01'),
      },
      {
        username: 'spam_user',
        email: 'spam@example.com',
        blockedDate: new Date('2024-01-10'),
        reason: 'Toplu spam aktivitesi',
        blockedBy: 'system',
        status: 'permanent',
        blockedUntil: null,
      },
      {
        username: 'ali_karaca',
        email: 'ali@example.com',
        blockedDate: new Date('2024-02-01'),
        reason: 'Küfürlü dil',
        blockedBy: 'admin',
        status: 'active',
        blockedUntil: null,
      },
      {
        username: 'melis_ay',
        email: 'melis@example.com',
        blockedDate: new Date('2024-03-10'),
        reason: 'Reklam spamı',
        blockedBy: 'moderator',
        status: 'temporary',
        blockedUntil: new Date('2024-09-01'),
      },
      {
        username: 'toxic_gamer',
        email: 'toxic@example.com',
        blockedDate: new Date('2024-03-15'),
        reason: 'Hakaret ve tehdit',
        blockedBy: 'admin',
        status: 'permanent',
        blockedUntil: null,
      },
      {
        username: 'fake_account',
        email: 'fake@example.com',
        blockedDate: new Date('2024-04-01'),
        reason: 'Sahte hesap',
        blockedBy: 'system',
        status: 'active',
        blockedUntil: null,
      },
    ],
  });

  await prisma.message.createMany({
    data: [
      {
        sender: 'system',
        title: 'Sistem bakım bildirimi',
        type: 'system',
        message: '15 Ocak 2025 tarihinde sistem bakımı yapılacaktır. Bakım süresi boyunca hizmet kesintisi yaşanabilir.',
        status: 'read',
        createdAt: new Date('2025-01-14T14:20:00Z'),
        userId: null,
      },
      {
        sender: 'zeynep.kaya',
        title: 'Harika bir özellik önerisi',
        type: 'feedback',
        message: 'Dark mode özelliği eklenebilir mi? Gece kullanımı için çok faydalı olur. Ayrıca bildirim ayarları daha detaylandırılabilir.',
        status: 'replied',
        createdAt: new Date('2025-01-13T16:45:00Z'),
        userId: 'user_135',
      },
      {
        sender: 'can.demir',
        title: 'Şifremi unuttuğum için yardım',
        type: 'support',
        message: 'Hesabıma giriş yapamıyorum. Şifre sıfırlama e-postası da gelmiyor. Lütfen yardım edebilir misiniz?',
        status: 'pending',
        createdAt: new Date('2025-01-12T09:15:00Z'),
        userId: 'user_132',
      },
      {
        sender: 'elif.ozkan',
        title: 'Ödeme işleminde hata',
        type: 'bug',
        message: 'Kredi kartı ile ödeme yaparken sürekli hata alıyorum. Farklı kartlar denedim ama sorun devam ediyor.',
        status: 'read',
        createdAt: new Date('2025-01-11T11:30:00Z'),
        userId: 'user_133',
      },
      {
        sender: 'system',
        title: 'Güvenlik güncellemesi',
        type: 'system',
        message: 'Sistemimizde güvenlik güncellemesi yapıldı. Tüm kullanıcıların şifrelerini yenilemesi önerilir.',
        status: 'read',
        createdAt: new Date('2025-01-10T08:00:00Z'),
        userId: null,
      },
      {
        sender: 'fatma.yurt',
        title: 'Profil fotoğrafı yükleyemiyorum',
        type: 'bug',
        message: 'Profil fotoğrafımı değiştirmeye çalışıyorum ama hata veriyor. Dosya boyutu 2MB altında ve JPG formatında.',
        status: 'pending',
        createdAt: new Date('2025-01-09T15:20:00Z'),
        userId: 'user_130',
      },
      {
        sender: 'emre.ak',
        title: 'Bildirimler çok fazla geliyor',
        type: 'feedback',
        message: 'Günde 10-15 bildirim geliyor, azaltılabilir mi? Özellikle pazarlama bildirimleri çok sık.',
        status: 'read',
        createdAt: new Date('2025-01-08T12:10:00Z'),
        userId: 'user_129',
      },
      {
        sender: 'selin.dag',
        title: 'Premium hesap sorunu',
        type: 'support',
        message: 'Premium hesap aldım ama özellikler aktif olmadı. Ödeme yapıldı ama hesabım hala ücretsiz görünüyor.',
        status: 'replied',
        createdAt: new Date('2025-01-07T18:30:00Z'),
        userId: 'user_131',
      },
      {
        sender: 'system',
        title: 'Yeni özellik duyurusu',
        type: 'system',
        message: 'Artık görevlerinizi arkadaşlarınızla paylaşabilirsiniz! Sosyal özellikler aktif edildi.',
        status: 'read',
        createdAt: new Date('2025-01-06T10:00:00Z'),
        userId: null,
      },
      {
        sender: 'murat.koc',
        title: 'Mobil uygulama çok yavaş',
        type: 'bug',
        message: 'Android uygulaması çok yavaş açılıyor. Bazen 30 saniye beklemek zorunda kalıyorum.',
        status: 'pending',
        createdAt: new Date('2025-01-05T14:15:00Z'),
        userId: 'user_134',
      },
      {
        sender: 'ayse.demir',
        title: 'Harika uygulama!',
        type: 'feedback',
        message: 'Uygulamayı çok beğendim. Özellikle streak özelliği motivasyonumu artırıyor. Teşekkürler!',
        status: 'replied',
        createdAt: new Date('2025-01-04T11:30:00Z'),
        userId: 'user_123',
      },
      {
        sender: 'system',
        title: 'Veri yedekleme tamamlandı',
        type: 'system',
        message: 'Haftalık veri yedekleme işlemi başarıyla tamamlandı. Tüm kullanıcı verileri güvende.',
        status: 'read',
        createdAt: new Date('2025-01-03T02:00:00Z'),
        userId: null,
      },
      {
        sender: 'kemal.yilmaz',
        title: 'Hesap silme talebi',
        type: 'support',
        message: 'Hesabımı silmek istiyorum. GDPR kapsamında tüm verilerimin silinmesini talep ediyorum.',
        status: 'pending',
        createdAt: new Date('2025-01-02T16:45:00Z'),
        userId: 'user_136',
      },
      {
        sender: 'gamze.ozturk',
        title: 'Bildirim sesi değiştirilemiyor',
        type: 'bug',
        message: 'Bildirim sesini değiştirmeye çalışıyorum ama ayarlar kaydedilmiyor. Her seferinde varsayılan ses geliyor.',
        status: 'read',
        createdAt: new Date('2025-01-01T09:20:00Z'),
        userId: 'user_135',
      },
      {
        sender: 'system',
        title: 'Yılbaşı kutlaması',
        type: 'system',
        message: 'Yeni yılınız kutlu olsun! 2025 yılında daha fazla başarı dileriz.',
        status: 'read',
        createdAt: new Date('2025-01-01T00:00:00Z'),
        userId: null,
      },
    ],
  });

  // Additional messages with user relationships
  await prisma.message.createMany({
    data: [
      {
        sender: 'ahmet.yilmaz',
        title: 'Uygulama çok yavaş çalışıyor',
        type: 'bug',
        message: 'Mobil uygulamada sayfa geçişleri çok yavaş oluyor. Özellikle ana sayfadan profil sayfasına geçerken 5-6 saniye beklemek zorunda kalıyorum.',
        status: 'pending',
        createdAt: new Date('2025-01-15T10:30:00Z'),
        userId: 'user_123',
      },
      {
        sender: 'mehmet.sari',
        title: 'Görev tamamlama sorunu',
        type: 'bug',
        message: 'Görevimi tamamladım ama sistem kaydetmiyor. Streak\'im sıfırlandı.',
        status: 'pending',
        createdAt: new Date('2025-01-16T08:15:00Z'),
        userId: 'user_129',
      },
      {
        sender: 'ali.yurt',
        title: 'Premium özellikler hakkında soru',
        type: 'support',
        message: 'Premium üyeliğin avantajları nelerdir? Detaylı bilgi alabilir miyim?',
        status: 'replied',
        createdAt: new Date('2025-01-17T13:45:00Z'),
        userId: 'user_131',
      },
    ],
  });

  // Task
  await prisma.task.createMany({
    data: [
      {
        title: 'Günlük Meditasyon Rutini',
        description: '10 dakikalık nefes egzersizi yaparak zihnini sakinleştir.',
        status: 'active',
        aiConfidence: 92,
        userId: 'user_123',
        userName: 'Ahmet K.',
        slipId: 'slip_001',
        createdDate: new Date('2025-01-20'),
        dueDate: new Date('2025-01-22'),
        category: 'Mindfulness',
        difficulty: 'easy',
      },
      {
        title: 'Soğuk Duş Challenge',
        description: '3 dakikalık soğuk duş al.',
        status: 'active',
        aiConfidence: 87,
        userId: 'user_129',
        userName: 'Mehmet S.',
        slipId: 'slip_002',
        createdDate: new Date('2025-01-19'),
        dueDate: new Date('2025-01-21'),
        category: 'Physical',
        difficulty: 'medium',
      },
      {
        title: 'Günlük Journaling',
        description: 'Bugünkü duygularını yaz.',
        status: 'completed',
        aiConfidence: 95,
        userId: 'user_123',
        userName: 'Ahmet K.',
        slipId: 'slip_003',
        createdDate: new Date('2025-01-18'),
        dueDate: new Date('2025-01-20'),
        category: 'Mental',
        difficulty: 'easy',
      },
      {
        title: 'Sosyal Aktivite Planla',
        description: 'Bu hafta sonu arkadaşlarınla buluş.',
        status: 'expired',
        aiConfidence: 78,
        userId: 'user_131',
        userName: 'Ali Y.',
        slipId: null,
        createdDate: new Date('2025-01-17'),
        dueDate: new Date('2025-01-19'),
        category: 'Social',
        difficulty: 'medium',
      },
      {
        title: 'Telefon Detox Saati',
        description: 'Akşam 8-10 arası telefonunu kapalı tut.',
        status: 'active',
        aiConfidence: 89,
        userId: 'user_129',
        userName: 'Mehmet S.',
        slipId: 'slip_004',
        createdDate: new Date('2025-01-21'),
        dueDate: new Date('2025-01-23'),
        category: 'Digital',
        difficulty: 'hard',
      },
      {
        title: 'Yeni Kitap Oku',
        description: 'Bu hafta yeni bir kitap bitir.',
        status: 'active',
        aiConfidence: 85,
        userId: 'user_130',
        userName: 'Zeynep K.',
        slipId: 'slip_005',
        createdDate: new Date('2025-01-22'),
        dueDate: new Date('2025-01-28'),
        category: 'Personal Development',
        difficulty: 'medium',
      },
      {
        title: 'Erken Uyanma Challange',
        description: 'Bu hafta her gün 6:30da uyan.',
        status: 'active',
        aiConfidence: 76,
        userId: 'user_132',
        userName: 'Burak T.',
        slipId: 'slip_006',
        createdDate: new Date('2025-01-23'),
        dueDate: new Date('2025-01-30'),
        category: 'Lifestyle',
        difficulty: 'hard',
      },
      {
        title: 'Günlük 5 Bin Adım',
        description: 'Her gün en az 5000 adım at.',
        status: 'completed',
        aiConfidence: 91,
        userId: 'user_133',
        userName: 'Ayşe M.',
        slipId: 'slip_007',
        createdDate: new Date('2025-01-15'),
        dueDate: new Date('2025-01-20'),
        category: 'Physical',
        difficulty: 'easy',
      },
      {
        title: 'Haftalık Temizlik',
        description: 'Evini baştan sona temizle.',
        status: 'expired',
        aiConfidence: 82,
        userId: 'user_134',
        userName: 'Cem K.',
        slipId: null,
        createdDate: new Date('2025-01-12'),
        dueDate: new Date('2025-01-14'),
        category: 'Lifestyle',
        difficulty: 'medium',
      },
      {
        title: 'Yeni Yemek Tarifi Dene',
        description: 'Daha önce yapmadığın bir yemek yap.',
        status: 'active',
        aiConfidence: 88,
        userId: 'user_135',
        userName: 'Gizem A.',
        slipId: 'slip_008',
        createdDate: new Date('2025-01-24'),
        dueDate: new Date('2025-01-26'),
        category: 'Creative',
        difficulty: 'medium',
      },
    ],
  });

  // BlockedIP
  await prisma.blockedIP.createMany({
    data: [
      {
        ip: '192.168.1.100',
        reason: 'Brute force attack',
        blockedAt: new Date('2024-01-25T14:30:00Z'),
        blockedBy: 'Auto-system',
        attempts: 15,
        location: 'İstanbul, TR',
        status: 'active',
      },
      {
        ip: '45.123.45.67',
        reason: 'Spam activity',
        blockedAt: new Date('2024-01-24T09:15:00Z'),
        blockedBy: 'admin',
        attempts: 8,
        location: 'Unknown',
        status: 'active',
      },
      {
        ip: '203.45.67.89',
        reason: 'Suspicious behavior',
        blockedAt: new Date('2024-01-23T16:45:00Z'),
        blockedBy: 'moderator',
        attempts: 12,
        location: 'Moscow, RU',
        status: 'temporary',
      },
      {
        ip: '10.0.0.1',
        reason: 'DDoS attack',
        blockedAt: new Date('2024-02-01T11:00:00Z'),
        blockedBy: 'system',
        attempts: 30,
        location: 'Ankara, TR',
        status: 'permanent',
      },
      {
        ip: '172.16.0.2',
        reason: 'Multiple failed logins',
        blockedAt: new Date('2024-02-05T16:20:00Z'),
        blockedBy: 'admin',
        attempts: 20,
        location: 'Izmir, TR',
        status: 'active',
      },
      {
        ip: '88.99.100.101',
        reason: 'Automated bot activity',
        blockedAt: new Date('2024-02-10T12:30:00Z'),
        blockedBy: 'system',
        attempts: 50,
        location: 'Berlin, DE',
        status: 'permanent',
      },
      {
        ip: '77.88.99.110',
        reason: 'SQL injection attempts',
        blockedAt: new Date('2024-02-12T15:45:00Z'),
        blockedBy: 'admin',
        attempts: 25,
        location: 'London, UK',
        status: 'active',
      },
    ],
  });

  // Notification
  await prisma.notification.createMany({
    data: [
      {
        title: 'Günlük Motivasyon',
        message: 'Bugün harika şeyler başaracaksın! 💪',
        type: 'motivation',
        targetGroup: 'all',
        scheduledAt: new Date('2025-01-25T08:00:00Z'),
        status: 'active',
        frequency: 'daily',
      },
      {
        title: 'Haftalık Görev Hatırlatması',
        message: 'Bu hafta tamamlaman gereken görevlerin var!',
        type: 'dailyReminder',
        targetGroup: 'active_users',
        scheduledAt: new Date('2025-01-27T09:00:00Z'),
        status: 'active',
        frequency: 'weekly',
      },
      {
        title: 'Premium Üyelik Kampanyası',
        message: '%50 indirimle premium üye ol!',
        type: 'marketing',
        targetGroup: 'free_users',
        scheduledAt: new Date('2025-01-28T12:00:00Z'),
        status: 'active',
        frequency: 'once',
      },
      {
        title: 'Sistem Bakım Bildirimi',
        message: 'Yarın gece 02:00-04:00 arası sistem bakımı yapılacaktır.',
        type: 'system',
        targetGroup: 'all',
        scheduledAt: new Date('2025-01-26T20:00:00Z'),
        status: 'completed',
        frequency: 'once',
      },
      {
        title: 'Streak Kaybetme Uyarısı',
        message: 'Dikkat! Streak\'in sona ermek üzere.',
        type: 'dailyReminder',
        targetGroup: 'streak_users',
        scheduledAt: new Date('2025-01-25T19:00:00Z'),
        status: 'active',
        frequency: 'daily',
      },
      {
        title: 'Yeni Özellik Duyurusu',
        message: 'Artık arkadaşlarınla görev paylaşabilirsin!',
        type: 'system',
        targetGroup: 'all',
        scheduledAt: new Date('2025-01-24T10:00:00Z'),
        status: 'completed',
        frequency: 'once',
      },
      {
        title: 'Hafta Sonu Motivasyonu',
        message: 'Hafta sonu da hedeflerinden vazgeçme! 🎯',
        type: 'motivation',
        targetGroup: 'weekend_active',
        scheduledAt: new Date('2025-01-25T10:00:00Z'),
        status: 'active',
        frequency: 'weekly',
      },
      {
        title: 'Aylık İstatistik Raporu',
        message: 'Bu ay ne kadar geliştiğini görmek ister misin?',
        type: 'dailyReminder',
        targetGroup: 'premium_users',
        scheduledAt: new Date('2025-02-01T09:00:00Z'),
        status: 'active',
        frequency: 'monthly',
      },
      {
        title: 'Yaz Kampanyası',
        message: 'Yaz aylarında daha aktif ol, ödüller kazan!',
        type: 'marketing',
        targetGroup: 'all',
        scheduledAt: new Date('2025-06-01T12:00:00Z'),
        status: 'paused',
        frequency: 'once',
      },
      {
        title: 'Güvenlik Güncellemesi',
        message: 'Hesap güvenliği için şifreni güncellemeyi unutma.',
        type: 'system',
        targetGroup: 'all',
        scheduledAt: new Date('2025-01-30T15:00:00Z'),
        status: 'active',
        frequency: 'monthly',
      },
    ],
  });

  // BillingLog
  await prisma.billingLog.createMany({
    data: [
      {
        userId: 'user_123',
        userName: 'Ahmet Kaya',
        amount: 29.99,
        currency: 'TRY',
        status: 'success',
        paymentMethod: 'credit_card',
        description: 'Premium Aylık Abonelik',
      },
      {
        userId: 'user_129',
        userName: 'Mehmet Sari',
        amount: 299.99,
        currency: 'TRY',
        status: 'success',
        paymentMethod: 'credit_card',
        description: 'Premium Yıllık Abonelik',
      },
      {
        userId: 'user_131',
        userName: 'Ali Yurt',
        amount: 29.99,
        currency: 'TRY',
        status: 'failed',
        paymentMethod: 'credit_card',
        description: 'Premium Aylık Abonelik - Kart Reddedildi',
      },
      {
        userId: 'user_130',
        userName: 'Zeynep Koca',
        amount: 9.99,
        currency: 'TRY',
        status: 'success',
        paymentMethod: 'paypal',
        description: 'Ekstra Görev Paketi',
      },
      {
        userId: 'user_132',
        userName: 'Burak Tekin',
        amount: 49.99,
        currency: 'TRY',
        status: 'pending',
        paymentMethod: 'bank_transfer',
        description: 'Premium 2 Aylık Paket',
      },
      {
        userId: 'user_133',
        userName: 'Ayşe Mutlu',
        amount: 29.99,
        currency: 'TRY',
        status: 'success',
        paymentMethod: 'credit_card',
        description: 'Premium Aylık Abonelik',
      },
      {
        userId: 'user_134',
        userName: 'Cem Kara',
        amount: 199.99,
        currency: 'TRY',
        status: 'failed',
        paymentMethod: 'credit_card',
        description: 'Premium 6 Aylık Paket - Yetersiz Bakiye',
      },
      {
        userId: 'user_135',
        userName: 'Gizem Ak',
        amount: 14.99,
        currency: 'TRY',
        status: 'success',
        paymentMethod: 'google_pay',
        description: 'Özel Tema Paketi',
      },
      {
        userId: 'user_136',
        userName: 'Fatih Demir',
        amount: 299.99,
        currency: 'TRY',
        status: 'success',
        paymentMethod: 'credit_card',
        description: 'Premium Yıllık Abonelik',
      },
      {
        userId: 'user_123',
        userName: 'Ahmet Kaya',
        amount: 19.99,
        currency: 'TRY',
        status: 'pending',
        paymentMethod: 'apple_pay',
        description: 'Motivasyon Ses Paketi',
      },
    ],
  });

  // Product
  await prisma.product.createMany({
    data: [
      {
        name: 'Premium Aylık',
        description: 'Tüm özelliklere aylık erişim',
        price: 29.99,
        currency: 'TRY',
        type: 'subscription',
        duration: '1 month',
        subscribers: 1250,
        isActive: true,
      },
      {
        name: 'Premium Yıllık',
        description: 'Tüm özelliklere yıllık erişim (%30 indirimli)',
        price: 299.99,
        currency: 'TRY',
        type: 'subscription',
        duration: '1 year',
        subscribers: 850,
        isActive: true,
      },
      {
        name: 'Ekstra Görev Paketi',
        description: '50 adet özel görev',
        price: 9.99,
        currency: 'TRY',
        type: 'one_time',
        duration: null,
        subscribers: 0,
        isActive: true,
      },
      {
        name: 'Özel Tema Paketi',
        description: '10 adet premium tema',
        price: 14.99,
        currency: 'TRY',
        type: 'one_time',
        duration: null,
        subscribers: 0,
        isActive: true,
      },
      {
        name: 'Premium 6 Aylık',
        description: '6 aylık premium erişim',
        price: 199.99,
        currency: 'TRY',
        type: 'subscription',
        duration: '6 months',
        subscribers: 420,
        isActive: true,
      },
      {
        name: 'Motivasyon Ses Paketi',
        description: 'Günlük motivasyon ses dosyaları',
        price: 19.99,
        currency: 'TRY',
        type: 'one_time',
        duration: null,
        subscribers: 0,
        isActive: true,
      },
      {
        name: 'Öğrenci Premium',
        description: 'Öğrenciler için %50 indirimli premium',
        price: 14.99,
        currency: 'TRY',
        type: 'subscription',
        duration: '1 month',
        subscribers: 320,
        isActive: true,
      },
      {
        name: 'Aile Paketi',
        description: '4 kişiye kadar premium erişim',
        price: 89.99,
        currency: 'TRY',
        type: 'subscription',
        duration: '1 month',
        subscribers: 180,
        isActive: true,
      },
      {
        name: 'Beta Test Paketi',
        description: 'Yeni özelliklere erken erişim',
        price: 5.99,
        currency: 'TRY',
        type: 'subscription',
        duration: '1 month',
        subscribers: 45,
        isActive: false,
      },
      {
        name: 'Kişisel Koç Paketi',
        description: 'AI kişisel koç özelliği',
        price: 49.99,
        currency: 'TRY',
        type: 'one_time',
        duration: null,
        subscribers: 0,
        isActive: true,
      },
    ],
  });

  // Role
  await prisma.role.createMany({
    data: [
      {
        name: 'Super Admin',
        description: 'Tüm sistem yetkilerine sahip',
        permissions: ['user_management', 'system_settings', 'billing', 'content_management', 'analytics', 'security'],
        userCount: 2,
      },
      {
        name: 'Admin',
        description: 'Genel yönetim yetkileri',
        permissions: ['user_management', 'content_management', 'analytics', 'support'],
        userCount: 5,
      },
      {
        name: 'Moderator',
        description: 'İçerik moderasyon yetkileri',
        permissions: ['content_management', 'user_moderation', 'support'],
        userCount: 12,
      },
      {
        name: 'Support',
        description: 'Kullanıcı destek yetkileri',
        permissions: ['support', 'user_view', 'ticket_management'],
        userCount: 8,
      },
      {
        name: 'Content Creator',
        description: 'İçerik oluşturma yetkileri',
        permissions: ['content_create', 'content_edit', 'task_management'],
        userCount: 15,
      },
      {
        name: 'Analytics',
        description: 'Veri analizi yetkileri',
        permissions: ['analytics', 'reports', 'user_statistics'],
        userCount: 4,
      },
      {
        name: 'Marketing',
        description: 'Pazarlama ve kampanya yetkileri',
        permissions: ['campaign_management', 'notification_send', 'user_segmentation'],
        userCount: 6,
      },
      {
        name: 'Developer',
        description: 'Sistem geliştirme yetkileri',
        permissions: ['system_settings', 'api_access', 'debug_mode'],
        userCount: 10,
      },
    ],
  });

  // Permission
  await prisma.permission.createMany({
    data: [
      {
        name: 'user_management',
        description: 'Kullanıcı hesaplarını yönetme',
        category: 'User Management',
        rolesCount: 3,
      },
      {
        name: 'system_settings',
        description: 'Sistem ayarlarını değiştirme',
        category: 'System',
        rolesCount: 2,
      },
      {
        name: 'billing',
        description: 'Fatura ve ödeme işlemleri',
        category: 'Finance',
        rolesCount: 1,
      },
      {
        name: 'content_management',
        description: 'İçerik yönetimi ve düzenleme',
        category: 'Content',
        rolesCount: 4,
      },
      {
        name: 'analytics',
        description: 'Analitik verilerine erişim',
        category: 'Analytics',
        rolesCount: 3,
      },
      {
        name: 'security',
        description: 'Güvenlik ayarları ve logları',
        category: 'Security',
        rolesCount: 1,
      },
      {
        name: 'support',
        description: 'Kullanıcı destek işlemleri',
        category: 'Support',
        rolesCount: 3,
      },
      {
        name: 'user_moderation',
        description: 'Kullanıcı moderasyon işlemleri',
        category: 'Moderation',
        rolesCount: 1,
      },
      {
        name: 'user_view',
        description: 'Kullanıcı bilgilerini görüntüleme',
        category: 'User Management',
        rolesCount: 1,
      },
      {
        name: 'ticket_management',
        description: 'Destek taleplerini yönetme',
        category: 'Support',
        rolesCount: 1,
      },
      {
        name: 'content_create',
        description: 'Yeni içerik oluşturma',
        category: 'Content',
        rolesCount: 1,
      },
      {
        name: 'content_edit',
        description: 'Mevcut içerikleri düzenleme',
        category: 'Content',
        rolesCount: 1,
      },
      {
        name: 'task_management',
        description: 'Görev yönetimi',
        category: 'Tasks',
        rolesCount: 1,
      },
      {
        name: 'reports',
        description: 'Rapor oluşturma ve görüntüleme',
        category: 'Analytics',
        rolesCount: 1,
      },
      {
        name: 'user_statistics',
        description: 'Kullanıcı istatistikleri',
        category: 'Analytics',
        rolesCount: 1,
      },
      {
        name: 'campaign_management',
        description: 'Pazarlama kampanyalarını yönetme',
        category: 'Marketing',
        rolesCount: 1,
      },
      {
        name: 'notification_send',
        description: 'Bildirim gönderme',
        category: 'Communication',
        rolesCount: 1,
      },
      {
        name: 'user_segmentation',
        description: 'Kullanıcı segmentasyonu',
        category: 'Marketing',
        rolesCount: 1,
      },
      {
        name: 'api_access',
        description: 'API erişimi ve yönetimi',
        category: 'Development',
        rolesCount: 1,
      },
      {
        name: 'debug_mode',
        description: 'Debug modu erişimi',
        category: 'Development',
        rolesCount: 1,
      },
    ],
  });

  // Activity
  await prisma.activity.createMany({
    data: [
      {
        type: 'login',
        message: 'Kullanıcı giriş yaptı',
        details: 'IP: 192.168.1.1, Tarayıcı: Chrome',
        timestamp: new Date('2025-01-24T10:15:00Z'),
        color: 'green',
        userId: 'user_123',
      },
      {
        type: 'premium_purchase',
        message: 'Premium abonelik satın alındı',
        details: 'Paket: Premium Aylık, Ödeme: Kredi Kartı',
        timestamp: new Date('2025-01-23T14:30:00Z'),
        color: 'purple',
        userId: 'user_129',
      },
      {
        type: 'task_completed',
        message: 'Görev tamamlandı',
        details: 'Görev: Günlük Meditasyon Rutini',
        timestamp: new Date('2025-01-23T08:45:00Z'),
        color: 'blue',
        userId: 'user_123',
      },
      {
        type: 'streak_milestone',
        message: '20 günlük streak başarısı',
        details: 'Kullanıcı 20 günlük streak\'e ulaştı',
        timestamp: new Date('2025-01-22T21:00:00Z'),
        color: 'orange',
        userId: 'user_131',
      },
      {
        type: 'account_update',
        message: 'Profil bilgileri güncellendi',
        details: 'Güncellenen alanlar: Avatar, Bildirim tercihleri',
        timestamp: new Date('2025-01-22T16:20:00Z'),
        color: 'gray',
        userId: 'user_130',
      },
      {
        type: 'system',
        message: 'Sistem bakımı tamamlandı',
        details: 'Planlı bakım: Veritabanı optimizasyonu',
        timestamp: new Date('2025-01-21T03:30:00Z'),
        color: 'blue',
        userId: null,
      },
      {
        type: 'security_alert',
        message: 'Şüpheli giriş denemesi',
        details: 'IP: 45.123.45.67, 5 başarısız deneme',
        timestamp: new Date('2025-01-20T22:10:00Z'),
        color: 'red',
        userId: 'user_132',
      },
      {
        type: 'feedback',
        message: 'Kullanıcı geri bildirimi gönderildi',
        details: 'Konu: Uygulama performansı, Puan: 4/5',
        timestamp: new Date('2025-01-20T13:45:00Z'),
        color: 'green',
        userId: 'user_133',
      },
      {
        type: 'new_feature',
        message: 'Yeni özellik kullanıldı',
        details: 'Özellik: Arkadaşlarla görev paylaşımı',
        timestamp: new Date('2025-01-19T17:30:00Z'),
        color: 'purple',
        userId: 'user_129',
      },
      {
        type: 'achievement',
        message: 'Başarı kazanıldı',
        details: 'Başarı: İlk Hafta Tamamlandı, Ödül: 100 puan',
        timestamp: new Date('2025-01-19T09:15:00Z'),
        color: 'gold',
        userId: 'user_130',
      },
    ],
  });

  console.log('Seed data created successfully!');
}

main()
  .then(() => {
    console.log('Seed completed!');
    return prisma.$disconnect();
  })
  .catch((e) => {
    console.error(e);
    return prisma.$disconnect();
  });